config/routes.rb
Gormify::Application.routes.draw do
  get "payments/express"
  get "songs/download"
  resources :payments

  get "sessions/new"
  get "users/basket"

  resources :users
  
  resources :orders
  
  resources :line_items
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :artists do
    resources :albums
  end
  
  resources :albums do
    resources :songs
  end
  
  
  resources :songs do
    get :download
  end
  
  match "/orders/:id", :to => "orders#show", :as => "/cart"
  
  match "/verify/:id", :to => "users#verify"
  
  match "/cart", :to => "users#basket", :as => "/cart"
  
  match '/basket', :to => 'orders#basket'
  
  match '/purchases', :to => 'orders#purchases'
      
  match '/newartist', :to => 'artists#new'
  match '/manage', :to => 'artists#manage'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/terms', :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
 

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :bio, :name, :user_id, :photo
  
  belongs_to :user
  
  has_many :albums, :dependent => :destroy
  
  validates :name, :presence => true, :length => { :maximum => 50}
  validates :bio, :presence => true, :length => { :maximum => 140}
  validates :user_id, :presence => true
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end      
  end
  
  default_scope :order => 'artists.created_at DESC'
  
  #paperclip
  has_attached_file :photo,
     :styles => {
       :thumb=> "50x50#",
       :small  => "100x100>" },
     :storage => :s3,
     :s3_credentials => "#{Rails.root}/config/s3.yml",
     :s3_permissions => 'public-read',
     :path => "/artistphotos/:style/:id/:filename"
     
     validates_attachment_presence :photo
     
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => :destory
  
  def index
    @title = "Browse Artists" 
    @artists = Artist.search(params[:search])
  end
  
  def manage
    @user = @current_user
    @title = "Artist Manager"
    
    @artists = @user.artists.paginate(:page => params[:page])
    
    if @artists.size == 0
      render :action => "empty"
    end
  end
  
  def edit
    @title = "Edit artist"
    @artist = Artist.find(params[:id])
  end
  
  def create
    @artist = current_user.artists.new(params[:artist])
    
    if @artist.save
      flash[:success] = "Artist created!"
      redirect_to @artist
    else
      @title = "Artist"
      render 'new'
    end
  end
  
  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      flash[:success] = "Artist Updated"
      redirect_to @artist
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    flash[:success] = "Artist destroyed."
    redirect_back_or artists_path
  end
  
  def new
    @artist = Artist.new
    @title = "Band Sign Up"
  end
  
  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums.paginate(:page => params[:page])
    @title = @artist.name
  end
  
  private
  
    def authorized_user
      @artist = Artist.find(params[:id])
      redirect_to artist_url unless current_user?(@artist.user)
    end
  
end

app/views/artists/_artist.html.erb
<div>
	<div class="artist">
		<%= link_to artist.name, artist %>
	
		<% if artist.user == current_user %>
			| <%= link_to 'Edit', edit_artist_path(artist) %>
		<% end %>
		
		<% if current_user.admin? || artist.user == current_user %>
			| <%= link_to 'Delete?', artist, :method => :delete %>
		<% end %>
	</div>
</div>

app/views/artists/edit.html.erb
<h4>Add an Artist or Band</h4>

<%= form_for @artist, :html => { :multipart => true } do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		 <%= f.label :name, "Upload a photo that represents your band:" %><br />
		<div>
		<p class="warning">This photo will be used to identify your band around the website, and on your profile page.</p>
		</div>
		 <%= f.file_field :photo %>
	</div>
	<div class="field">
		<%= f.label :bio, "Why don't you tell us about yourself?" %><br />
		<div>
		<p class="warning">Keep it brief (under 140 characters!)</p>
		</div>
		<%= f.text_area :bio %>
	</div>
	<div class = "actions">
		<%= f.submit "Update"%>
	</div>
<% end %>

app/views/artists/empty.html.erb
You currently don't manage any artists. Click the link in the footer to create one.

app/views/artists/index.html.erb
<h4>Browse Artists</h4>


<%= form_tag songs_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil, :class => "button" %>
	</p>
<% end %>

<ul class="artists">
	<%= render @artists %>
</ul>

app/views/artists/manage.html.erb
<p>Use this area to manage your artists and bands.</p>
		<div class="artists">
			<%= render @artists %>
		</div>
		<%= will_paginate @artists %>

app/views/artists/new.html.erb
<h3>Add an Artist or Band</h3>

<p>Fill in the form below in order to start uploading your own music and start making some cash!</p>
<%= form_for @artist, :html => { :multipart => true } do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name, "What's your artist/band called?" %><br />
		<div>
		<p class="warning">Make sure this is correct, once you've claimed it you won't be able to change it!</p>
		</div>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		 <%= f.label :name, "Upload a photo that represents your band:" %><br />
		<div>
		<p class="warning">This photo will be used to identify your band around the website, and on your profile page.</p>
		</div>
		 <%= f.file_field :photo, :class => "button" %>
	</div>
	<div class="field">
		<%= f.label :bio, "Why don't you tell us about yourself?" %><br />
		<div>
		<p class="warning">You can keep this brief for now, you can update it at any time</p>
		</div>
		<%= f.text_area :bio %>
	</div>
	<div class="actions">
		<%= f.submit "Sign this artist up", :class => "button"%>
	</div>
<% end %>

app/views/artists/show.html.erb
<div class="profile">
	<div class = "artistinfo">
		<% if @artist.photo.exists? then %>
		<%= image_tag @artist.photo.url(:thumb) %>
		<% end %>
		<h4><%= @artist.name %></h4>
		<%= @artist.bio %>
	</div>
	<div>
	<%= link_to "Add Album", new_artist_album_path(@artist) %>
	
	<%= link_to "View Sales Stats", manage_path %>
	</div>
	
	<div class=albums>
	<% unless @artist.albums.empty? %>
		<div class = "albumlist">
			<%= render @albums %>
		</div>
		<%= will_paginate @albums %>
	<% end %>
	</div>
</div>