config/routes.rb
Gormify::Application.routes.draw do
  get "payments/express"
  get "songs/download"
  resources :payments

  get "sessions/new"
  get "users/basket"

  resources :users
  
  resources :orders
  
  resources :line_items
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :artists do
    resources :albums
  end
  
  resources :albums do
    resources :songs
  end
  
  
  resources :songs do
    get :download
  end
  
  match "/orders/:id", :to => "orders#show", :as => "/cart"
  
  match "/verify/:id", :to => "users#verify"
  
  match "/cart", :to => "users#basket", :as => "/cart"
  
  match '/basket', :to => 'orders#basket'
  
  match '/purchases', :to => 'orders#purchases'
      
  match '/newartist', :to => 'artists#new'
  match '/manage', :to => 'artists#manage'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/terms', :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
 

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :terms
  
  has_many :artists, :dependent => :destroy
  has_many :orders
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :password, :presence => true,
                       :confirmation => true,
                       :length      => { :within =>6..40 }
                     
   validates_acceptance_of :terms
   
   before_save :encrypt_password
   
   def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end      
  end
   
   
   # Return true if the user's password matchs the submitted password
   def has_password? (submitted_password)
     encrypted_password == encrypt(submitted_password)
   end
   
   def self.authenticate(email, submitted_password)
     user = find_by_email(email)
     return nil if user.nil?
     return user if user.has_password?(submitted_password)
   end
   
   def self.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     (user && user.salt == cookie_salt) ? user : nil #crazy boolean
   end
   
   
   private
   
     def encrypt_password
       self.salt = make_salt if new_record?
       self.encrypted_password = encrypt(password)
       
       self.verify_token = encrypt2(Time.now.utc)
     end
     
     def secure_hash2(string)
       Digest::SHA1.hexdigest(string)
     end
     
     def encrypt2(string)
       secure_hash2("#{salt}--#{string}")
     end
     
     def encrypt(string)
       secure_hash("#{salt}--#{string}")
     end
     
     def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
     end
     
     def secure_hash(string)
       Digest::SHA2.hexdigest(string)
     end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def verify
    
    #@user = User.find_by_verify_token(params[:id])
    @user = User.find(:all, :conditions => {:verify_token => params[:id]})
    
    if @user.nil?
      render :action => "notverified"
    end
    
    found = 0
      
     @user.each_with_index do |user, i|
          user.update_attribute(:status, 1)
          found = 2
      end
     
     
    if found == 0
      render :action => "notverified"
    end
    
    if found == 1
      render :action => "reverified"
    end
    
    if found == 2
      render :action => "verify"
    end
    
  end
  
  def index
    @title = "Browse users" 
    @users = User.search(params[:search])
  end
  
  def show
    @user = User.find_by_id(params[:id])
    if @user.nil?
      render :action => "notfound"
    else
    @artists = @user.artists.paginate(:page => params[:page])
    @title = @user.name
    end
  end
  
  def new
    @user = User.new
    @title = "Sign Up"
  end
  
  def create
    @user = User.new(params[:user])
    @user.status = 0
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the sample App!"
      MisocureMailer.welcome_email(@user).deliver
      redirect_to @user
    else
      @title = "Sign Up"
      @user.password = nil 
      @user.password_confirmation = nil 
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  private
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.name,
    :class => 'gravatar',
    :gravatar => options)
  end
end

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>
	
	<% if current_user.admin? %>
	| <%= link_to 'Delete?', user, :method => :delete %>
	
	<% end %>
</li>

app/views/users/edit.html.erb
<h4>Edit user</h4>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" class="button">change</a>
	</div>
	<div class = "field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	
	<div class = "field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	
	<div class = "actions">
		<%= f.submit "Update", :class => "button"%>
	</div>
<% end %>
	

app/views/users/index.html.erb
<h4>Browse Users</h4>

<%= form_tag users_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil, :class => "button" %>
	</p>
<% end %>

<ul class="users">
	
	<%= render @users %>
	
</ul>

app/views/users/new.html.erb
<h4>Sign Up</h4>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
	<%= f.check_box :terms %>
	<%= f.label :terms, "I accept the terms of service" %><br />
	<%= link_to "Terms of Service", terms_path, :class => "button" %>
	</div>
	
	<div class="actions">
		<%= f.submit "Sign up", :class => "button"%>
	</div>
<% end %>
	

app/views/users/notfound.html.erb
User doesn't exist :(

app/views/users/notverified.html.erb
Are you trying to verify your email address? If so there has been a weird error.

Please contact support!

app/views/users/reverified.html.erb
You already verified your account...well this is awkward.

app/views/users/show.html.erb
<div class="profile">
	<div class = "main">
	<h2>
	<%= gravatar_for @user %>
	<%= @user.name %>
	</div>
	
	
	
	</h2> 
	<div class = "sidebar round"> 
		<strong>Name</strong>   <%= @user.name %><br />
		<strong>URL</strong> <%= link_to user_path(@user), @user %><br />
		<strong>Artists</strong> <%= @user.artists.count %>
	</div>
</div>

app/views/users/verify.html.erb
That's you all verified. Go forth youngling!