config/routes.rb
Gormify::Application.routes.draw do
  get "payments/express"
  get "songs/download"
  resources :payments

  get "sessions/new"
  get "users/basket"

  resources :users
  
  resources :orders
  
  resources :line_items
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :artists do
    resources :albums
  end
  
  resources :albums do
    resources :songs
  end
  
  
  resources :songs do
    get :download
  end
  
  match "/orders/:id", :to => "orders#show", :as => "/cart"
  
  match "/verify/:id", :to => "users#verify"
  
  match "/cart", :to => "users#basket", :as => "/cart"
  
  match '/basket', :to => 'orders#basket'
  
  match '/purchases', :to => 'orders#purchases'
      
  match '/newartist', :to => 'artists#new'
  match '/manage', :to => 'artists#manage'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/terms', :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
 

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  
  has_many :line_items
  
  has_many :songs, :through => :line_items
  
  has_one :payment

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => :destory
  
  def index
   
  end

  def purchases
    @orders = current_user.orders.find_all_by_status(1)
    
    if @orders.size == 0
      render :action => "empty"
    end
  end
  
  def basket
    @user = @current_user
    @title = "Basket"
    @order = current_user.orders.find_by_status(0)
    
     if !@order
      @order = current_user.orders.new
      @order.status = 0
      @order.total = 0.00
      @order.save
    end
  end
  
  def create
    @order = current_user.orders.new(params[:order])
    @order.status = 0
    @order.total = 0.00
    if @order.save
      flash[:success] = "Artist created!"
      redirect_to root_path
    else
      flash.now[:message] = @order.errors.first 
      render 'pages/home'
    end
  end
  
  def destroy
    @order = current_user.orders.find_by_status(0)
    @order.destroy
    
    flash[:success] = "Your Cart is now empty. Better get shopping buddy!"
    
    redirect_to songs_path
   
  end
  
  def new
    
  end
  
  def show
    @order = Order.find(params[:id])  
  end
  
  private
    def authorized_user
      
    end
  
end

app/views/orders/_order.html.erb
<% if order.status == 0 %>

<table id="line_items">
  <tr>
    <th>Name</th>
    <th class="price">Price</th>
  </tr>
  <% for line_item in order.line_items %>
    <tr>
      <td><%=h line_item.song.name %></td>
      <td class="price"><%= number_to_currency(line_item.song.price, :unit => "&pound;") %></td>
    </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Total: <%= number_to_currency order.total, :unit => "&pound;" %>
    </td>
  </tr>
</table>
<% else %>

<% for line_item in order.line_items %>
    <tr>
      <td><%=h line_item.song.name %></td>
      <td class="download"><%= link_to "Download", song_download_path(line_item.song) %></td>
    </tr>
<% end %>
  
<% end %>

app/views/orders/basket.html.erb
<div class="order">
	<%= render @order %>
</div>
<div class="round">
<%= link_to 'Empty Cart', @order, method: :delete, :class => "button delete"  %>

<p>
  <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), payments_express_path %>
</p>
</div>

app/views/orders/empty.html.erb
After you purchase songs you'll be able to redownload your music here!

app/views/orders/purchases.html.erb
Your past purchases

<div class="order">
		
	<%= render @orders %>
	
	
</div>

app/views/orders/show.html.erb
<%= @order.id %>