config/routes.rb
Gormify::Application.routes.draw do
  get "payments/express"
  get "songs/download"
  resources :payments

  get "sessions/new"
  get "users/basket"

  resources :users
  
  resources :orders
  
  resources :line_items
  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :artists do
    resources :albums
  end
  
  resources :albums do
    resources :songs
  end
  
  
  resources :songs do
    get :download
  end
  
  match "/orders/:id", :to => "orders#show", :as => "/cart"
  
  match "/verify/:id", :to => "users#verify"
  
  match "/cart", :to => "users#basket", :as => "/cart"
  
  match '/basket', :to => 'orders#basket'
  
  match '/purchases', :to => 'orders#purchases'
      
  match '/newartist', :to => 'artists#new'
  match '/manage', :to => 'artists#manage'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/terms', :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'
 

end

app/views/layouts/_footer.html.erb
<footer>
<nav class ="round">
<ul>
	<li><%= link_to "About", about_path %></li>
	<li><%= link_to "Contact", contact_path %></li>
	<% if signed_in? %>
	<li><%= link_to "Manage a Band or Artist?", newartist_path %></li>
	<%end%>
	<li><a href="http://www.benjgorman.com">Benjamin Gomrman</a></li>
	</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="main_nav">
<%= link_to logo, root_path %>
<nav class = "round">
<ul>
<% if signed_in? %>
<li><%= link_to "Home", root_path, :class => "menu_button"  %></li>
<li><%= link_to "Artists", artists_path, :class => "menu_button"  %></li>
<li><%= link_to "Albums", albums_path, :class => "menu_button"  %></li>
<li><%= link_to "Songs", songs_path, :class => "menu_button"  %></li>
<li><%= link_to "Settings", edit_user_path(current_user), :class => "menu_button"  %></li>
<% end %>
</ul>
<ul>
<% if signed_in? %>
<Li><%= link_to "Manage Artists", manage_path, :class => "menu_button"  %>
<li><%= link_to "View Purchases", purchases_path, :class => "menu_button"  %></i>
<li><%= link_to "View Basket", basket_path, :class => "menu_button"  %></i>
<li><%= link_to "Sign Out", signout_path, :method => :delete, :class => "menu_button"  %></li>
<% else %>
<li><%= link_to "Sign in", signin_path, :class => "menu_button"  %></i>
<% end %>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<scrpt src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/bottom_header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
          <!--PUT NEW STUFF IN HERE -->
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <!--<%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>